### ISSUE TITLE
Latex error: CSLreferences undefined

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#184]
I'm having a compilation error when I run `bookdown::render_book("abstract.Rmd")`

The error is:

```
! LaTeX Error: Environment CSLReferences undefined.

Error: LaTeX failed to compile chimera_project_manuscript.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See chimera_project_manuscript.log for more info.
Please delete chimera_project_manuscript.Rmd after you finish debugging the error.
```

There is a long thread on rmarkdown [Pandoc 2.8 error "! LaTeX Error: Environment cslreferences undefined."
](https://github.com/rstudio/rmarkdown/issues/1649).

I tried their fixes in `.formatting/tempate.tex` and still got the same error.

```
> pandoc_version()
[1] ‘2.11.2’
```

@DimmestP are you still able to compile the manuscript? Any ideas about something I might have missed?

**Comment by DimmestP** [comment]
I was using an older version of pandocs so I didn't have this problem. I have now updated my version and get the same message. The original solution in the linked issue doesn't work as pandocs has updated again since. I have now copied the correct changes from the latest pandoc latex template and I can render the pdf again.

**Comment by ewallace** [comment]
Oh brilliant, did you commit & push the fix?

**Comment by DimmestP** [comment]
I have committed an update to the template file, if this works for you then close.

**Comment by ewallace** [comment]
It works, thanks!
