### ISSUE TITLE
filepaths in qPCR for promoter-terminator swaps

### ISSUE THREAD

**Issue by ewallace** [DimmestP/chimera_project_manuscript#51]
In qPCR analysis for promoter-terminator swaps:
`/raw_data_analysis/code/raw_qpcr_analysis/promoter_terminator_swaps/pRPS3_pPGK1_pSRO9_tvariable_three_bio_rep.Rmd`

I'm having a filepath issue in `load_plates` chunk, line 111; I think needs to be fixed with `here`.

**Comment by jauxillos** [comment]
I'm updating this. Some minor issue with loading of amplification and melt curve data to

**Comment by DimmestP** [comment]
Just to recap:

Jamie has fixed the file path issue but there are some remaining bugs with the amplification and melt curve chunks which will take a bit more time to fix. We have temporarily removed them so that the end figure can still be recreated (I've just accepted the pull request to the master branch).

We will let you know when the amplification and melt curve chunks have been fixed.
